{
 "title": "API Mini Health Monitor",
 "tags": [
  "fastapi",
  "rq",
  "redis"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "🚀 Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  },
  {
   "title": "✅ Jobs Finished",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jobs_finished_total" }
   ]
  },
  {
   "title": "🚫 Rate-Limited Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "rate_limited_total" }
   ]
  },
  {
   "title": "📦 Queue Length",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "queue_length{queue=\"default\"}"
    }
   ]
  }
 ]
}